info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
server:
  port: 8080
logging:
  file: /opt/logs/spring-cloud-config-demo-client.log
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG